require: rubocop-rspec

# Avoid methods longer than 30 lines of code
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  ExcludedMethods: ['controllers', 'describe', 'context']
Layout/LineLength:
  Max: 200
  IgnoredPatterns: ['(When|Given|Then)', '(get|post|put)']
Naming/PredicateName:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Documentation:
  Exclude: ['**/*']
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/HookArgument:
  EnforcedStyle: each
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Max: 3
Layout/EndOfLine:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator: 
  Enabled: false
Lint/DeprecatedOpenSSLConstant: 
  Enabled: false
Lint/MixedRegexpCaptureTypes: 
  Enabled: false
Lint/RaiseException: 
  Enabled: false
Lint/StructNewOverride: 
  Enabled: false
Style/AccessorGrouping: 
  Enabled: false
Style/BisectedAttrAccessor: 
  Enabled: false
Style/ExponentialNotation: 
  Enabled: false
Style/HashEachMethods: 
  Enabled: false
Style/HashTransformKeys: 
  Enabled: false
Style/HashTransformValues: 
  Enabled: false
Style/RedundantAssignment: 
  Enabled: false
Style/RedundantFetchBlock: 
  Enabled: false
Style/RedundantRegexpCharacterClass: 
  Enabled: false
Style/RedundantRegexpEscape: 
  Enabled: false
Style/SlicingWithRange: 
  Enabled: false
